-- Phase 1 RBAC core: use a hand-written enum swap rather than prisma db push.
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'COORDINATOR';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'TECH_LEAD';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'PR_HEAD';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'OPERATIONS_HEAD';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'TREASURER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'ALUMNI';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'VISITOR';

UPDATE "User" SET "role" = 'COORDINATOR' WHERE "role"::text = 'ADMIN';
UPDATE "User" SET "role" = 'TECH_LEAD' WHERE "role"::text = 'MODERATOR';
UPDATE "User" SET "role" = 'MEMBER' WHERE "role"::text = 'VERIFIED_AUTHOR';

CREATE TYPE "Role_new" AS ENUM ('COORDINATOR','TECH_LEAD','PR_HEAD','OPERATIONS_HEAD','TREASURER','MEMBER','ALUMNI','VISITOR');
ALTER TABLE "User" ALTER COLUMN "role" DROP DEFAULT;
ALTER TABLE "User" ALTER COLUMN "role" TYPE "Role_new" USING ("role"::text::"Role_new");
ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'VISITOR';
DROP TYPE "Role";
ALTER TYPE "Role_new" RENAME TO "Role";

DO $$ BEGIN
  CREATE TYPE "VerificationStatus" AS ENUM ('UNVERIFIED','PENDING','VERIFIED','REJECTED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "verificationStatus" "VerificationStatus" NOT NULL DEFAULT 'VERIFIED';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "isVerified" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "rollNumber" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "branch" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "batch" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "memberTitle" TEXT;
DO $$ BEGIN
  CREATE TYPE "MemberSection" AS ENUM ('COORDINATORS','CORE','TEAM');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "memberSection" "MemberSection" DEFAULT 'TEAM';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "socialLinks" JSONB;
UPDATE "User" SET "isVerified" = true WHERE "role" <> 'VISITOR';

ALTER TABLE "AuditLog" ADD COLUMN IF NOT EXISTS "target" TEXT;
ALTER TABLE "AuditLog" ADD COLUMN IF NOT EXISTS "meta" JSONB;
UPDATE "AuditLog" SET "target" = "entityId" WHERE "target" IS NULL;
UPDATE "AuditLog" SET "meta" = "metadata" WHERE "meta" IS NULL AND "metadata" IS NOT NULL;